INTRODUCTION:

In this project, we analyze retail store transaction data to understand customer purchasing behavior and identify patterns that can help improve supermarket layout and product placement. The dataset contains information such as transaction ID, customer ID, product category, item name, price per unit, quantity purchased, total spending, payment method, and purchase location.

During the initial stage of the project, the dataset is loaded and explored using Python libraries such as Pandas, NumPy, and Matplotlib. The purpose of this step is to understand the structure of the data, inspect the columns, identify missing values, and observe basic statistical information. This initial exploration helps ensure that the dataset is suitable for further analysis.

By performing this preliminary analysis, we gain insights into the dataset's characteristics and prepare the data for the next stages of the project, which include data cleaning, exploratory data analysis, and discovering relationships between different variables. These insights will ultimately help in understanding customer buying patterns and optimizing supermarket layout strategies.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

These libraries are imported to perform data analysis and visualization.

Pandas is used to load and manipulate the dataset.

NumPy is used for numerical operations.

Matplotlib is used to create graphs and visualizations.

In [2]:
df = pd.read_csv("/content/retail_store_sales.csv")

This line reads the CSV dataset file and loads it into a Pandas DataFrame called df, which allows us to perform analysis on the data.

In [3]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False


The head() function displays the first five rows of the dataset.
This helps us quickly understand the structure of the data and the values present in each column.

In [4]:
df.tail()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

The tail() function displays the last five rows of the dataset.
This helps confirm that the dataset has been loaded correctly and allows us to check the ending records.

In [5]:
df.shape

(12575, 11)

The shape attribute returns the number of rows and columns in the dataset.
This helps us understand the size of the dataset.

In [6]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='object')

This line displays the names of all the columns present in the dataset.
It helps us understand what features are available for analysis.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

The info() function provides detailed information about the dataset, including:

Column names:

Data types

Number of non-null values

Memory usage

This helps identify missing values and data types.

In [8]:
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

The describe() function generates statistical information for numerical columns such as:

Mean

Standard deviation

Minimum and maximum values

Quartiles

This helps understand the overall distribution of the data.

In [9]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

This line counts the number of missing values in each column.
It helps identify which columns require data cleaning or handling of missing values.

---



---

In [10]:
df['Category'].unique()

array(['Patisserie', 'Milk Products', 'Butchers', 'Beverages', 'Food',
       'Furniture', 'Electric household essentials',
       'Computers and electric accessories'], dtype=object)

The unique() function shows all different product categories present in the dataset.
This helps understand the types of products sold in the store.

In [13]:
print("Payment Method Count:")
print(df['Payment Method'].value_counts())

Payment Method Count:
Payment Method
Cash              4310
Digital Wallet    4144
Credit Card       4121
Name: count, dtype: int64

The value_counts() function counts how many times each payment method appears in the dataset.
This helps analyze customer payment preferences.

# **Overall summary**:

This code loads the retail store dataset and performs an initial inspection of the data. It checks the dataset structure, column names, data types, statistical summaries, and missing values. This preliminary exploration helps understand the dataset before performing further analysis such as data cleaning and exploratory data analysis.